### ISSUE TITLE
Create django website for generating reviews

### ISSUE THREAD

**Issue by daniel-acuna** [titipata/yelp_dataset_challenge#8]
Interface should be super simplistic. We should use something like this project: http://www.mattboldt.com/demos/typed-js/

**Comment by titipata** [comment]
Should we create it separately (new repository) or right here?

**Comment by daniel-acuna** [comment]
right here i think

**Comment by daniel-acuna** [comment]
Closed by 7bede85afcfda68f24f12bbb52e35e1353ed8e8b
